DROP TABLE IF EXISTS websites;
DROP TABLE IF EXISTS tocrawl;

CREATE TABLE websites (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  link TEXT UNIQUE NOT NULL,
  title TEXT
);


CREATE TABLE tocrawl (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  link TEXT UNIQUE NOT NULL
);
